version: '3'
services:
  grafana:
    image: "grafana/grafana"
    ports:
      - "3333:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=viewer
  influxdb:
    image: "influxdb"
    command: "influxd"
    volumes:
      - .:/var/lib/influxdb
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
      - influxdb
    depends_on:
      - influxdb
    environment:
      - INFLUX_URL=influxdb
      - GRAFANA_URL=http://localhost:3333
      - MONGO_URL=mongodb://mongo:27017/meteor
  mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    volumes:
      - .:/var/lib/mongodb
